ARACHNE = 0
CELERA = 1
ALL_ASSEM = -1
NOTHING = -2

SCAFFOLDS = 10
UDEF_SCAFFOLDS = 11
CONTIGS = 12

SEARCH_SCAFFOLDS = "Scaffold"
SEARCH_UDEF_SCAFFOLDS = "Undefined scaffold"
SEARCH_CONTIGS = "Contig"